JSON_API_VERSION = 1

FOERR_JSON_KEY_ID = "id"
FOERR_JSON_KEY_SYMBOL_LEGACY = "legacy_symbol"
FOERR_JSON_KEY_TEXTURE = "txt"
FOERR_JSON_KEY_TEXTURE_DELIM = "txt_delim"
FOERR_JSON_KEY_TEXTURE_DELIM_OFFSET = "txt_delim_offset"
FOERR_JSON_KEY_OFFSET = "offset"
FOERR_JSON_KEY_VARIANT = "var"
FOERR_JSON_KEY_BLEND = "blend"
FOERR_JSON_KEY_MAIN_CNT = "main_cnt"
FOERR_JSON_KEY_LIGHT_CNT = "light_cnt"
FOERR_JSON_KEY_ALPHA = "alpha"
FOERR_JSON_KEY_COLOR = "color"
FOERR_JSON_KEY_SOLIDS = "solids"
FOERR_JSON_KEY_OTHER = "other"
FOERR_JSON_KEY_IS_RIGHT = "is_right"
FOERR_JSON_KEY_API_VERSION = "api_version"
FOERR_JSON_KEY_VERSION = "version"
FOERR_JSON_KEY_ROOMS = "rooms"
FOERR_JSON_KEY_COORDS = "coords"
FOERR_JSON_KEY_CELLS = "cells"
FOERR_JSON_KEY_BACK_OBJS = "back_objs"
FOERR_JSON_KEY_FAR_BACK_OBJS = "far_back_objs"
FOERR_JSON_KEY_BACK_HOLES = "back_holes"
#FOERR_JSON_KEY_OBJS = "objs"
FOERR_JSON_KEY_BACKWALL = "backwall"
FOERR_JSON_KEY_LIQUID_LEVEL = "liquid_level"
FOERR_JSON_KEY_LIQUID_SYMBOL = "liquid_symbol"
FOERR_JSON_KEY_TYPE = "type"
FOERR_JSON_KEY_BACKGROUND_FULL = "background_full"
FOERR_JSON_KEY_IS_START = "is_start"
FOERR_JSON_KEY_OFFSET_LEFT = "offset_left"
FOERR_JSON_KEY_SPAWN_COORDS = "spawn_coords"

ROOM_WIDTH_WITH_BORDER = 48
ROOM_HEIGHT_WITH_BORDER = 25

IN_DELIM = '.'
OUT_DELIM = '|'
SYMBOL_EMPTY = '_'
SYMBOL_UNKNOWN = '?'

TXT_TYPE_MAIN = 0
TXT_TYPE_HOLE = 1
TXT_TYPE_LIGHT = 2

PATH_OBJS_BACK = "texture/objects_back"
FILE_OBJS_JSON = "objs.json"
