JSON_API_VERSION = 1

FOERR_JSON_KEY_SYMBOL_LEGACY = "legacy_symbol"
FOERR_JSON_KEY_TEXTURE = "txt"
FOERR_JSON_KEY_SOLIDS = "solids"
FOERR_JSON_KEY_OTHER = "other"
FOERR_JSON_KEY_IS_RIGHT = "is_right"
FOERR_JSON_KEY_API_VERSION = "api_version"
FOERR_JSON_KEY_ROOMS = "rooms"
FOERR_JSON_KEY_COORDS = "coords"
FOERR_JSON_KEY_CELLS = "cells"
FOERR_JSON_KEY_BACKWALL = "backwall"
FOERR_JSON_KEY_TYPE = "type"
FOERR_JSON_KEY_BACKGROUND_FULL = "background_full"
FOERR_JSON_KEY_IS_START = "is_start"
FOERR_JSON_KEY_OFFSET_LEFT = "offset_left"

FOERR_PATH_CELL_TEXTURES = "res/texture/cells"

ROOM_WIDTH_WITH_BORDER = 48
ROOM_HEIGHT_WITH_BORDER = 25

LADDER_LEFT_OFFSET_LEFT = -2
LADDER_RIGHT_OFFSET_LEFT = 21

IN_DELIM = '.'
OUT_DELIM = '|'
SYMBOL_EMPTY = '_'
SYMBOL_UNKNOWN = '?'
