// SPDX-License-Identifier: GPL-3.0-only
//
// (c) 2024 h67ma <szycikm@gmail.com>

#pragma once

enum PipBuckPageType
{
	PIPB_PAGE_LOAD,
	PIPB_PAGE_SAVE,
	PIPB_PAGE_SETTINGS,
	PIPB_PAGE_CONTROLS,
	PIPB_PAGE_LOG,
	PIPB_PAGE_STATUS_MAIN,
	PIPB_PAGE_SKILLS,
	PIPB_PAGE_PERKS,
	PIPB_PAGE_EFFECTS,
	PIPB_PAGE_HEALTH,
	PIPB_PAGE_WEAPONS,
	PIPB_PAGE_ARMOR,
	PIPB_PAGE_EQUIPMENT,
	PIPB_PAGE_INVENTORY_OTHER,
	PIPB_PAGE_AMMO,
	PIPB_PAGE_MAP,
	PIPB_PAGE_WORLD,
	PIPB_PAGE_QUESTS,
	PIPB_PAGE_NOTES,
	PIPB_PAGE_ENEMIES,
};
