name: clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang_format:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y clang-format-13
    - name: Run clang-format
      run: |
        SOURCES=$(find ${{github.workspace}}/src -type f | grep "\.cpp$\|\.hpp$\|\.c$\|\.h$\|\.h\.in$")
        clang-format-13 -style=file -Werror --dry-run $SOURCES
